import torch
import json
import torch.nn as nn
from torch.nn import functional as F
import torch.optim as optim
from tokenizers import Tokenizer
from .FineTuningmodel import Transformer
from .utils import pad_sequence, create_mask
from .paths import TOKENIZER_PATH, Advice_PATH, Params_Path



tokenize = Tokenizer.from_file(TOKENIZER_PATH)

vocab_size = tokenize.get_vocab_size()
pad_token = tokenize.token_to_id('[PAD]')
unk_token = tokenize.token_to_id('[UNK]')
mask_token = tokenize.token_to_id('[MASK]')
bos_token  = tokenize.token_to_id("[BOS]")
eos_token = tokenize.token_to_id("[EOS]")
mask_spread = 0.15



AI_DISCLAIMER = "Note: This recommendation was generated by an AI system. Please follow the company's security policy if unsure."

with open(Advice_PATH,"r") as f:
    Response_map = json.load(f)

def generate_response(label): 
    response_data = Response_map[label]
    final_output = { "label": label,
    "recommended_action": response_data["recommended_action"],
    "user_advice": response_data["user_advice"]}
    return final_output







def prompt(input_text, model):
    if input_text == " " or input_text == "":
        return {
            "label": "unknown",
            "recommended_action" : "Proceed with caution. Unable to classify email type.", 
            "user_advice": "Avoid clicking any links or replying to the sender. Contact your IT team if unsure."
        }
    output = model.prompt(input_text, bos_token, eos_token, pad_sequence, pad_token,create_mask)


    result = generate_response(output)

    return result
